using System.Collections.Generic;

namespace FreelanceHunt_Parser
{
    public class Data
    {
        public const string token = "95f9c99b90ca9e178ca93f932b78131be1f11359";

        public static Dictionary<string, int> Skills = new Dictionary<string, int>();

        static Data()
        {
            Skills.Add("1C", 56);
            Skills.Add("3D graphics", 59);
            Skills.Add("3D modeling and visualization", 111);
            Skills.Add("Abstracts, diploma papers, course papers", 116);
            Skills.Add("Accounting services", 149);
            Skills.Add("Advertising", 138);
            Skills.Add("Animation", 91);
            Skills.Add("Application programming", 103);
            Skills.Add("C#", 24);
            Skills.Add("Apps for Android", 121);
            Skills.Add("Apps for iOS (iPhone/iPad)", 120);
            Skills.Add("Architectural desig", 108);
            Skills.Add("Article writing", 38);
            Skills.Add("Artwork", 141);
            Skills.Add("Audio processing", 102);
            Skills.Add("Audio/video editing", 113);
            Skills.Add("Banners", 41);
            Skills.Add("Blockchain", 182);
            Skills.Add("Business card design", 156);
            Skills.Add("Business consulting", 112);
            Skills.Add("C/C++", 2);
            Skills.Add("Chat bot development", 180);
            Skills.Add("Client management/CRM", 150);
            Skills.Add("CMS installation and configuration", 78);
            Skills.Add("Computer networking", 72);
            Skills.Add("Consulting", 154);
            Skills.Add("Content management", 104);
            Skills.Add("Contextual advertising", 127);
            Skills.Add("Copywriting", 76);
            Skills.Add("Corporate style", 77);
            Skills.Add("Customer support", 171);
            Skills.Add("Data parsing", 169);
            Skills.Add("Data processing", 178);
            Skills.Add("Databases", 86);
            Skills.Add("Delphi/Object Pascal", 177);
            Skills.Add("Designing", 64);
            Skills.Add("DevOps", 181);
            Skills.Add("Drawings and diagrams", 147);
            Skills.Add("Email marketing", 136);
            Skills.Add("Embedded systems and microcontrollers", 176);
            Skills.Add("Engineering", 148);
            Skills.Add("English", 79);
            Skills.Add("Exhibition booth design", 132);
            Skills.Add("Flash/Flex", 5);
            Skills.Add("FreeBSD", 48);
            Skills.Add("French", 158);
            Skills.Add("Gaming applications", 88);
            Skills.Add("Geographic information systems", 115);
            Skills.Add("German", 80);
            Skills.Add("Git/Mercurial", 54);
            Skills.Add("Go", 173);
            Skills.Add("Handmade", 142);
            Skills.Add("Hebrew", 166);
            Skills.Add("HTML/CSS", 124);
            Skills.Add("Icons and pixel graphics", 93);
            Skills.Add("Illustrations and drawings", 90);
            Skills.Add("Industrial design", 164);
            Skills.Add("Infographics", 172);
            Skills.Add("Information gathering", 170);
            Skills.Add("Interface design", 42);
            Skills.Add("Interior design", 106);
            Skills.Add("IP-telephony/VoIP", 62);
            Skills.Add("Italian", 82);
            Skills.Add("Java", 13);
            Skills.Add("JavaScript", 28);
            Skills.Add("Landscape design", 107);
            Skills.Add("Lead generation and sales", 162);
            Skills.Add("Legal services", 153);
            Skills.Add("Linux/Unix", 6);
            Skills.Add("Logo design", 17);
            Skills.Add("Mac OS / Objective - C", 146);
            Skills.Add("Machine learning", 175);
            Skills.Add("Marketing research", 94);
            Skills.Add("Microsoft .NET", 61);
            Skills.Add("Mobile apps design", 179);
            Skills.Add("Music", 100);
            Skills.Add("Naming and slogans", 123);
            Skills.Add("Node.js", 174);
            Skills.Add("Online stores and e-commerce", 68);
            Skills.Add("Outdoor advertising", 109);
            Skills.Add("Package design", 117);
            Skills.Add("Payment systems integration", 129);
            Skills.Add("Photo processing", 18);
            Skills.Add("Photography", 139);
            Skills.Add("PHP", 1);
            Skills.Add("Poems, songs, prose", 140);
            Skills.Add("Presentation development", 114);
            Skills.Add("Print design", 75);
            Skills.Add("Project management", 89);
            Skills.Add("Prototyping", 165);
            Skills.Add("Python", 22);
            Skills.Add("Recruitment", 159);
            Skills.Add("Rewriting", 125);
            Skills.Add("Ruby", 23);
            Skills.Add("Script writing", 163);
            Skills.Add("Search engine optimization", 14);
            Skills.Add("Search engine reputation management", 135);
            Skills.Add("Social media advertising", 133);
            Skills.Add("Social media marketing", 131);
            Skills.Add("Social media page design", 151);
            Skills.Add("Software protection and security", 65);
            Skills.Add("Software, website and game localization", 157);
            Skills.Add("Software/server configuration", 83);
            Skills.Add("Spanish", 84);
            Skills.Add("Speaker/Voice services", 143);
            Skills.Add("Swift", 160);
            Skills.Add("System administration", 39);
            Skills.Add("System programming", 85);
            Skills.Add("Teaser advertisements", 145);
            Skills.Add("Technical documentation", 97);
            Skills.Add("Testing and QA", 57);
            Skills.Add("Text editing and proofreading", 168);
            Skills.Add("Text translation", 37);
            Skills.Add("Transcribing", 122);
            Skills.Add("Tuition", 95);
            Skills.Add("Type/Font design", 152);
            Skills.Add("Vector graphics", 58);
            Skills.Add("Video advertising", 144);
            Skills.Add("Video processing", 101);
            Skills.Add("Video recording", 161);
            Skills.Add("Web design", 43);
            Skills.Add("Web programming", 99);
            Skills.Add("Website development", 96);
            Skills.Add("Website maintenance", 45);
            Skills.Add("Website SEO audit", 134);
            Skills.Add("Windows", 7);
        }
    }
}
